spring.application.name=OnlineIDE
server.port = 8081

<<<<<<< HEAD
spring.datasource.url = jdbc:postgresql://localhost:5432/OnlineIDE1
spring.datasource.username = postgres
spring.datasource.password=12345678
=======
spring.datasource.url = jdbc:postgresql://localhost:5432/OnlineIDE
spring.datasource.username = postgres
spring.datasource.password=Shree@123
>>>>>>> a472369 (code-update: added unit testing controller and repo layer)
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto = update

# to see in command line
spring.jpa.show-sql = true

#sql logs
spring.jpa.properties.hibernate.format_sql=true
