spring.config.import=file:env.properties

spring.application.name=OnlineIDE
server.port = 8081


spring.datasource.url = jdbc:postgresql://localhost:5432/OnlineIDE
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto = update

# to see in command line
spring.jpa.show-sql = true

#sql logs
spring.jpa.properties.hibernate.format_sql=true
